# Generated by Django 5.1.6 on 2025-06-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
