# Generated by Django 5.1.6 on 2025-06-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_background_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
    ]
