# Generated by Django 5.1.6 on 2025-06-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_column_options_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
