# Generated by Django 5.1.6 on 2025-06-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_column_options_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='board',
        ),
        migrations.RemoveField(
            model_name='column',
            name='position',
        ),
    ]
