# Generated by Django 5.1.6 on 2025-06-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_column_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(default='77c23c15-5f27-471f-9c04-e96e46533806', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards.board'),
            preserve_default=False,
        ),
    ]
