# Generated by Django 5.1.6 on 2025-06-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_column_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='position',
        ),
    ]
