# Generated by Django 5.1.6 on 2025-06-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_remove_task_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='column',
            new_name='columnId',
        ),
    ]
