# Generated by Django 5.1.6 on 2025-06-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_rename_column_task_columnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
