# Generated by Django 5.1.6 on 2025-06-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_board_workspace_alter_board_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
    ]
