# Generated by Django 5.1.6 on 2025-06-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_board_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='column',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
