# Generated by Django 5.1.6 on 2025-07-03 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_boardactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardactivity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='boards.task'),
        ),
    ]
